# Generated by Django 4.1.7 on 2023-03-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pets',
            new_name='Pet',
        ),
        migrations.RenameModel(
            old_name='Status',
            new_name='Stat',
        ),
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
    ]
