# Generated by Django 4.1.7 on 2023-03-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_pets_pet_rename_status_stat_rename_types_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='execution_status',
            new_name='sell',
        ),
    ]
